### ISSUE TITLE
[FEAT] CICD Workflow 추가하기

### ISSUE THREAD

**Issue by TEDD325** [TEDD325/airflow-practice#1]
## What
- 개발용 GCP Compute Engine 인스턴스에서 구성한 모든 사항을 배포 서버에 자동 구성하기 위한 CI workflows를 구성
- 개발용 GCP Compute Engine 인스턴스에서 repository로 push된 코드를 배포 서버에서 자동으로 CD workflows를 구성

## Why
- 배포 서버 환경 구성 자동화 및 개발 서버와의 환경 구성 통일
- 배포 자동화

## How
- .github/workflows 폴더 하위에 yaml 파일로 workflows를 정의한다.

## Trouble
- 배포 서버 환경 구성은 최초 처음에만 이루어져야 하도록 작성해야 한다.

## To-Do
- [x] .github/workflows 디렉토리 생성
- [x] yaml 설정 파일 생성(파일 이름 미정)
- [x] Repository 설정에서 필요한 Variable/Secrets 설정
- [x] Actions 테스트 및 yaml 파일 수정
