### ISSUE TITLE
[FEAT] docker-compose 설정

### ISSUE THREAD

**Issue by TEDD325** [TEDD325/airflow-practice#3]
## What
- docker-compose 설정을 통해, CloudSQL을 metadata DB로 설정

## Why
- 로컬의 DB가 아닌 GCP의 DB를 사용하기 위함

## How
- docker-compose 파일을 astro dev로 export한 후, yaml 파일을 커스터마이징

## Trouble
- CloudSQL과의 연결이 적절히 이루어지지 않을 수도 있음

## To-Do
- [ ] astro dev로 compose.yaml 파일 export
- [ ] compose.yaml 파일에서 PostgreSQL 관련 부분 모두 주석 또는 제거 처리
- [ ] compose.yaml 파일에서 CloudSQL Connection 관련 부분 추가
